---
# OPTIONAL TASKS (needed to run checks from the host machine)
# - name: Uncomment the GitLab IP whitelist line
#   replace:
#     path: /etc/gitlab/gitlab.rb
#     regexp: '^# (gitlab_rails\[''monitoring_whitelist''\] = \[.*)\]$'
#     replace: '\1, ''20.20.20.1'']'

# - name: Reconfigure GitLab
#   command: gitlab-ctl reconfigure

# - name: Restart unicorn
#   command: gitlab-ctl restart unicorn
#   retries: 2
# END OF OPTIONAL TASKS

- name: Check GitLab health
  uri:
    url: http://127.0.0.1/-/health
    return_content: yes
  # Register the output of the module in a variable
  register: gitlab_health

- name: Print GitLab health
  debug:
    msg: "{{ gitlab_health.content }}"

# Run the 2 other kind of health checks below

- name: Check Gitlab Readiness
  uri:
    url: http://127.0.0.1/-/readiness
    return_content: yes
  register: gitlab_readiness

#{"status":"ok","master_check":[{"status":"ok"}]}

- name: Print Gitlab Readiness ok
  debug:
    msg: "{{ gitlab_readiness.content }}"

- name: Print Gitlab Readiness not ok
  debug:
    msg: "custom error message"
  when: (gitlab_readiness.content|from_json)["status"] == "ok"

- name: Check Gitlab Liveness
  uri:
    url: http://127.0.0.1/-/liveness
    return_content: yes
  register: gitlab_liveness

- name: Print Gitlab Liveness
  debug:
    msg: "{{ gitlab_liveness.content }}"
